<a href="https://colab.research.google.com/github/vikrantyadav11234/NLP_Practice/blob/main/Text_Preprocessing_for_Customer_suppoert_on_twitter_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#
In any ML task, cleaning or preprocessing the data is important as model building if not more. and when it comes to unstructured data like text, this process is even more important.

Some of the common text preprocessing/ cleaning steps are:
* Lower casing
* Removal of punctuations
* Removal of stop words
* removal of frequent words
* Removal of rare words
* Number to words / ignoring numbers
* Stemming
* Lemmatization
* removal of emojis
* COnversion of emotion to words.
* Conversion of emojis to words.
* Removal of urls.
* Chat word conversions
* Spelling correction
* remove emoticons

In [ ]:
import pandas as pd
import numpy as np
import re
import spacy
import string

In [ ]:
import nltk

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d thoughtvector/customer-support-on-twitter

Dataset URL: https://www.kaggle.com/datasets/thoughtvector/customer-support-on-twitter
License(s): CC-BY-NC-SA-4.0
Downloading customer-support-on-twitter.zip to /content
 96% 161M/169M [00:02<00:00, 72.4MB/s]
100% 169M/169M [00:02<00:00, 70.1MB/s]

In [ ]:
import zipfile
zip_ref = zipfile.ZipFile("/content/customer-support-on-twitter.zip")
zip_ref.extractall('/content')
zip_ref.close()

In [ ]:
! ls "/content/twcs"

twcs.csv

In [ ]:
full_df= pd.read_csv("/content/twcs/twcs.csv", nrows=100000)
df= full_df[["text"]]
df['text']=df['text'].astype(str)
full_df.head()

<ipython-input-7-9c49447b5002>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text']=df['text'].astype(str)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [ ]:
df['text_lower'] = df['text'].str.lower()
df.head()

<ipython-input-8-5e40701d7bd7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text_lower'] = df['text'].str.lower()

,text,text_lower
0,@115712 I understand. I would like to assist y...,@115712 i understand. i would like to assist y...
1,@sprintcare and how do you propose we do that,@sprintcare and how do you propose we do that
2,@sprintcare I have sent several private messag...,@sprintcare i have sent several private messag...
3,@115712 Please send us a Private Message so th...,@115712 please send us a private message so th...
4,@sprintcare I did.,@sprintcare i did.

In [ ]:
df.head(25)

,text,text_lower
0,@115712 I understand. I would like to assist y...,@115712 i understand. i would like to assist y...
1,@sprintcare and how do you propose we do that,@sprintcare and how do you propose we do that
2,@sprintcare I have sent several private messag...,@sprintcare i have sent several private messag...
3,@115712 Please send us a Private Message so th...,@115712 please send us a private message so th...
4,@sprintcare I did.,@sprintcare i did.
5,@115712 Can you please send us a private messa...,@115712 can you please send us a private messa...
6,@sprintcare is the worst customer service,@sprintcare is the worst customer service
7,@115713 This is saddening to hear. Please shoo...,@115713 this is saddening to hear. please shoo...
8,@sprintcare You gonna magically change your co...,@sprintcare you gonna magically change your co...
9,@115713 We understand your concerns and we'd l...,@115713 we understand your concerns and we'd l...
10,@sprintcare Since I signed up with you....Sinc...,@sprintcare since i signed up with you....sinc...
11,@115713 H there! We'd definitely like to work ...,@115713 h there! we'd definitely like to work ...
12,@115714 y’all lie about your “great” connectio...,@115714 y’all lie about your “great” connectio...
13,@115715 Please send me a private message so th...,@115715 please send me a private message so th...
14,"@115714 whenever I contact customer support, t...","@115714 whenever i contact customer support, t..."
15,@115716 What information is incorrect? ^JK,@115716 what information is incorrect? ^jk
16,@Ask_Spectrum Would you like me to email you a...,@ask_spectrum would you like me to email you a...
17,@115716 Our department is part of the corporat...,@115716 our department is part of the corporat...
18,@Ask_Spectrum I received this from your corpor...,@ask_spectrum i received this from your corpor...
19,@115716 No thank you. ^JK,@115716 no thank you. ^jk
20,@Ask_Spectrum The correct way to do it is via ...,@ask_spectrum the correct way to do it is via ...
21,@Ask_Spectrum That is INCORRECT information I ...,@ask_spectrum that is incorrect information i ...
22,@115716 The information pertaining to the acco...,@115716 the information pertaining to the acco...
23,actually that's a broken link you sent me and ...,actually that's a broken link you sent me and ...
24,"@115717 Hello, My apologies for any frustratio...","@115717 hello, my apologies for any frustratio..."

# Removal of Punctuations

In [ ]:
PUNCT_TO_REMOVE = string.punctuation
print(PUNCT_TO_REMOVE)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [ ]:
def remove_punctuation(text):
  return text.translate(str.maketrans('','',PUNCT_TO_REMOVE))

df['text_to_punct']=df['text_lower'].apply(lambda text: remove_punctuation(text))
df.head()

<ipython-input-11-f51dbda66626>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text_to_punct']=df['text_lower'].apply(lambda text: remove_punctuation(text))

,text,text_lower,text_to_punct
0,@115712 I understand. I would like to assist y...,@115712 i understand. i would like to assist y...,115712 i understand i would like to assist you...
1,@sprintcare and how do you propose we do that,@sprintcare and how do you propose we do that,sprintcare and how do you propose we do that
2,@sprintcare I have sent several private messag...,@sprintcare i have sent several private messag...,sprintcare i have sent several private message...
3,@115712 Please send us a Private Message so th...,@115712 please send us a private message so th...,115712 please send us a private message so tha...
4,@sprintcare I did.,@sprintcare i did.,sprintcare i did

### Removal of stopwords

In [ ]:
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
', '.join(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

"i, me, my, myself, we, our, ours, ourselves, you, you're, you've, you'll, you'd, your, yours, yourself, yourselves, he, him, his, himself, she, she's, her, hers, herself, it, it's, its, itself, they, them, their, theirs, themselves, what, which, who, whom, this, that, that'll, these, those, am, is, are, was, were, be, been, being, have, has, had, having, do, does, did, doing, a, an, the, and, but, if, or, because, as, until, while, of, at, by, for, with, about, against, between, into, through, during, before, after, above, below, to, from, up, down, in, out, on, off, over, under, again, further, then, once, here, there, when, where, why, how, all, any, both, each, few, more, most, other, some, such, no, nor, not, only, own, same, so, than, too, very, s, t, can, will, just, don, don't, should, should've, now, d, ll, m, o, re, ve, y, ain, aren, aren't, couldn, couldn't, didn, didn't, doesn, doesn't, hadn, hadn't, hasn, hasn't, haven, haven't, isn, isn't, ma, mightn, mightn't, mustn, mustn't, needn, needn't, shan, shan't, shouldn, shouldn't, wasn, wasn't, weren, weren't, won, won't, wouldn, wouldn't"

In [ ]:
STOPWORDS = set(stopwords.words('english'))
def remove_stopwords(text):
  return  ' '.join([word for word in str(text).split() if not word in STOPWORDS])

df['text_to_stop']=df['text_to_punct'].apply(lambda text: remove_stopwords(text))
df.head()

<ipython-input-13-c232ad7ae437>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text_to_stop']=df['text_to_punct'].apply(lambda text: remove_stopwords(text))

,text,text_lower,text_to_punct,text_to_stop
0,@115712 I understand. I would like to assist y...,@115712 i understand. i would like to assist y...,115712 i understand i would like to assist you...,115712 understand would like assist would need...
1,@sprintcare and how do you propose we do that,@sprintcare and how do you propose we do that,sprintcare and how do you propose we do that,sprintcare propose
2,@sprintcare I have sent several private messag...,@sprintcare i have sent several private messag...,sprintcare i have sent several private message...,sprintcare sent several private messages one r...
3,@115712 Please send us a Private Message so th...,@115712 please send us a private message so th...,115712 please send us a private message so tha...,115712 please send us private message assist c...
4,@sprintcare I did.,@sprintcare i did.,sprintcare i did,sprintcare

### Removal of frequent words

In [ ]:
from collections import Counter
cnt = Counter()
for text in df['text_to_stop'].values:
  for word in text.split():
    cnt[word] += 1

cnt.most_common(10)

[('us', 15280),
 ('please', 14172),
 ('dm', 10290),
 ('help', 9181),
 ('hi', 8364),
 ('thanks', 7794),
 ('get', 7393),
 ('sorry', 6913),
 ('amazonhelp', 5916),
 ('know', 5443)]

In [ ]:
FREQWORDS= set ([w for (w,wc) in cnt.most_common(10)])
def remove_freqwords(text):
  return ' '.join([word for word in str(text).split() if word not in FREQWORDS])

df['text_to_ferq']= df['text_to_punct'].apply(lambda text: remove_freqwords(text))
df.head()

<ipython-input-16-46c0917be783>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text_to_ferq']= df['text_to_punct'].apply(lambda text: remove_freqwords(text))

,text,text_lower,text_to_punct,text_to_stop,text_to_ferq
0,@115712 I understand. I would like to assist y...,@115712 i understand. i would like to assist y...,115712 i understand i would like to assist you...,115712 understand would like assist would need...,115712 i understand i would like to assist you...
1,@sprintcare and how do you propose we do that,@sprintcare and how do you propose we do that,sprintcare and how do you propose we do that,sprintcare propose,sprintcare and how do you propose we do that
2,@sprintcare I have sent several private messag...,@sprintcare i have sent several private messag...,sprintcare i have sent several private message...,sprintcare sent several private messages one r...,sprintcare i have sent several private message...
3,@115712 Please send us a Private Message so th...,@115712 please send us a private message so th...,115712 please send us a private message so tha...,115712 please send us private message assist c...,115712 send a private message so that we can f...
4,@sprintcare I did.,@sprintcare i did.,sprintcare i did,sprintcare,sprintcare i did

In [ ]:
# Remove the rare words
n_rare_words = 20
RAREWORDS = set([w for (w,wc) in cnt.most_common()[:-n_rare_words-1:-1]])
print(RAREWORDS)
def remove_rarewords(text):
  return ' '.join([word for word in str(text).split() if word not in RAREWORDS])

df['text_to_rare']= df['text_to_ferq'].apply(lambda text: remove_rarewords(text))
df.head()

{'phone131027', 'httpstcoklebhaiotk', '230k', 'httpstcoldgvfgko7y', 'tale”', 'rajni', 'httpstcosxccepn7bl', 'knight’s', 'ulllrrrich', '7110', 'haveagainasked', '7109', 'lichtenstein', '144296', 'chaucer', 'therelets', 'enforcer', 'mailtemplate', 'httpstcoehp8tcbeds', '144295'}

<ipython-input-17-43ca9c9a8188>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text_to_rare']= df['text_to_ferq'].apply(lambda text: remove_rarewords(text))

,text,text_lower,text_to_punct,text_to_stop,text_to_ferq,text_to_rare
0,@115712 I understand. I would like to assist y...,@115712 i understand. i would like to assist y...,115712 i understand i would like to assist you...,115712 understand would like assist would need...,115712 i understand i would like to assist you...,115712 i understand i would like to assist you...
1,@sprintcare and how do you propose we do that,@sprintcare and how do you propose we do that,sprintcare and how do you propose we do that,sprintcare propose,sprintcare and how do you propose we do that,sprintcare and how do you propose we do that
2,@sprintcare I have sent several private messag...,@sprintcare i have sent several private messag...,sprintcare i have sent several private message...,sprintcare sent several private messages one r...,sprintcare i have sent several private message...,sprintcare i have sent several private message...
3,@115712 Please send us a Private Message so th...,@115712 please send us a private message so th...,115712 please send us a private message so tha...,115712 please send us private message assist c...,115712 send a private message so that we can f...,115712 send a private message so that we can f...
4,@sprintcare I did.,@sprintcare i did.,sprintcare i did,sprintcare,sprintcare i did,sprintcare i did

### Stemming

In [ ]:
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer('english')

def stem_words(text):
  return ' '.join([stemmer.stem(word) for word in text.split()])

df['text_to_stem']= df['text_to_rare'].apply(lambda text: stem_words(text))
df.head()

,text,text_lower,text_to_punct,text_to_stop,text_to_ferq,text_to_rare,text_to_stem
0,@115712 I understand. I would like to assist y...,@115712 i understand. i would like to assist y...,115712 i understand i would like to assist you...,115712 understand would like assist would need...,115712 i understand i would like to assist you...,115712 i understand i would like to assist you...,115712 i understand i would like to assist you...
1,@sprintcare and how do you propose we do that,@sprintcare and how do you propose we do that,sprintcare and how do you propose we do that,sprintcare propose,sprintcare and how do you propose we do that,sprintcare and how do you propose we do that,sprintcar and how do you propos we do that
2,@sprintcare I have sent several private messag...,@sprintcare i have sent several private messag...,sprintcare i have sent several private message...,sprintcare sent several private messages one r...,sprintcare i have sent several private message...,sprintcare i have sent several private message...,sprintcar i have sent sever privat messag and ...
3,@115712 Please send us a Private Message so th...,@115712 please send us a private message so th...,115712 please send us a private message so tha...,115712 please send us private message assist c...,115712 send a private message so that we can f...,115712 send a private message so that we can f...,115712 send a privat messag so that we can fur...
4,@sprintcare I did.,@sprintcare i did.,sprintcare i did,sprintcare,sprintcare i did,sprintcare i did,sprintcar i did

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

### Lemmatization

In [ ]:

from nltk.stem import WordNetLemmatizer
lemma = WordNetLemmatizer()
def lemma_words(text):
  return ' '.join([lemma.lemmatize(word) for word in str(text).split()])

df['text_to_lemma']= df['text_to_rare'].apply(lambda text: lemma_words(text))
df.head()

,text,text_lower,text_to_punct,text_to_stop,text_to_ferq,text_to_rare,text_to_stem,text_to_lemma
0,@115712 I understand. I would like to assist y...,@115712 i understand. i would like to assist y...,115712 i understand i would like to assist you...,115712 understand would like assist would need...,115712 i understand i would like to assist you...,115712 i understand i would like to assist you...,115712 i understand i would like to assist you...,115712 i understand i would like to assist you...
1,@sprintcare and how do you propose we do that,@sprintcare and how do you propose we do that,sprintcare and how do you propose we do that,sprintcare propose,sprintcare and how do you propose we do that,sprintcare and how do you propose we do that,sprintcar and how do you propos we do that,sprintcare and how do you propose we do that
2,@sprintcare I have sent several private messag...,@sprintcare i have sent several private messag...,sprintcare i have sent several private message...,sprintcare sent several private messages one r...,sprintcare i have sent several private message...,sprintcare i have sent several private message...,sprintcar i have sent sever privat messag and ...,sprintcare i have sent several private message...
3,@115712 Please send us a Private Message so th...,@115712 please send us a private message so th...,115712 please send us a private message so tha...,115712 please send us private message assist c...,115712 send a private message so that we can f...,115712 send a private message so that we can f...,115712 send a privat messag so that we can fur...,115712 send a private message so that we can f...
4,@sprintcare I did.,@sprintcare i did.,sprintcare i did,sprintcare,sprintcare i did,sprintcare i did,sprintcar i did,sprintcare i did

In [ ]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

True

In [ ]:
from nltk.corpus import wordnet
wordnet_map = {'N': wordnet.NOUN, "V":wordnet.VERB, "J":wordnet.ADJ, "R":wordnet.ADV}
def lemma_words(text):
  pos_tagged_text= nltk.pos_tag(text.split())
  return ' '.join([lemma.lemmatize(word, wordnet_map.get(pos[0],wordnet.NOUN)) for word, pos in pos_tagged_text])

df['text_to_pos_lemma']= df['text_to_rare'].apply(lambda text: lemma_words(text))

In [ ]:
df.head()

,text,text_lower,text_to_punct,text_to_stop,text_to_ferq,text_to_rare,text_to_stem,text_to_lemma,text_to_pos_lemma
0,@115712 I understand. I would like to assist y...,@115712 i understand. i would like to assist y...,115712 i understand i would like to assist you...,115712 understand would like assist would need...,115712 i understand i would like to assist you...,115712 i understand i would like to assist you...,115712 i understand i would like to assist you...,115712 i understand i would like to assist you...,115712 i understand i would like to assist you...
1,@sprintcare and how do you propose we do that,@sprintcare and how do you propose we do that,sprintcare and how do you propose we do that,sprintcare propose,sprintcare and how do you propose we do that,sprintcare and how do you propose we do that,sprintcar and how do you propos we do that,sprintcare and how do you propose we do that,sprintcare and how do you propose we do that
2,@sprintcare I have sent several private messag...,@sprintcare i have sent several private messag...,sprintcare i have sent several private message...,sprintcare sent several private messages one r...,sprintcare i have sent several private message...,sprintcare i have sent several private message...,sprintcar i have sent sever privat messag and ...,sprintcare i have sent several private message...,sprintcare i have send several private message...
3,@115712 Please send us a Private Message so th...,@115712 please send us a private message so th...,115712 please send us a private message so tha...,115712 please send us private message assist c...,115712 send a private message so that we can f...,115712 send a private message so that we can f...,115712 send a privat messag so that we can fur...,115712 send a private message so that we can f...,115712 send a private message so that we can f...
4,@sprintcare I did.,@sprintcare i did.,sprintcare i did,sprintcare,sprintcare i did,sprintcare i did,sprintcar i did,sprintcare i did,sprintcare i do

### Remove urls

In [ ]:
import re
def remove_urls(text):
  url_pattern = re.compile(r'https?://\S+|www\.\S+')
  return url_pattern.sub(r'', text)

In [ ]:
text= "Driverless AI NLP blog post on https://colab.research.google.com/drive/19ByfREt-8P2N-CSENWyQ8-g__8-apNjp#scrollTo=IQvbcGDWFajd"
remove_urls(text)

'Driverless AI NLP blog post on '

### Remove HTML Tags